---
apiVersion: v1
kind: Service
metadata:
  name: issue-creator
  namespace: github-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: issue-creator
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
