---
apiVersion: v1
kind: Service
metadata:
  name: ollama-tailscale
  namespace: ollama
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "ollama"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
  ports:
    - name: http
      port: 80
      targetPort: 11434
      protocol: TCP
