all:
  children:
    k3s_servers:
      hosts:
        nas2:
          ansible_host: nas2
          ansible_user: ed
          ansible_become: true
          ansible_become_method: sudo
    k3s_agents:
      hosts:
        desktop:
          ansible_host: desktop.taile9c9c.ts.net
          ansible_user: ed
          ansible_become: true
          ansible_become_method: sudo
