---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: litellm-secrets
  namespace: litellm
spec:
  organizationId: c046a20a-413d-4b54-8a56-b1790122c5ef
  secretName: litellm-secrets
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: 53904946-84fc-46dd-858b-b446001ff47a
      secretKeyName: LITELLM_MASTER_KEY
