---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-shim
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager-shim
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
