apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: {{ .Values.secrets.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "news.commonLabels" . | nindent 4 }}
spec:
  organizationId: {{ .Values.secrets.bitwardenOrganizationId }}
  secretName: {{ .Values.secrets.secretName }}
  authToken:
    secretName: {{ .Values.secrets.authToken.secretName }}
    secretKey: {{ .Values.secrets.authToken.secretKey }}
  map:
    {{- range .Values.secrets.mappings }}
    - bwSecretId: {{ .bwSecretId }}
      secretKeyName: {{ .envName }}
    {{- end }}
