#!/usr/bin/env python3
"""Regenerate gitops/manifests/dev-agent/payload-configmap.yaml from src/.

Source of truth = gitops/manifests/dev-agent/src/{run.sh,opencode.json}.
ConfigMap mirrors those file contents; run this script after edits.
"""

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC_DIR = REPO / "gitops/manifests/dev-agent/src"
DST = REPO / "gitops/manifests/dev-agent/payload-configmap.yaml"

FILES = {
    "run.sh": SRC_DIR / "run.sh",
    "opencode.json": SRC_DIR / "opencode.json",
}

HEADER = """---
# Auto-generated by scripts/regen-dev-agent-configmap.py from
# gitops/manifests/dev-agent/src/. Do not hand-edit; edit the source
# files and re-run the script.
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-agent-payload
  namespace: agents
data:
"""


def main() -> None:
    lines = [HEADER]
    for key, path in FILES.items():
        content = path.read_text()
        lines.append(f"  {key}: |\n")
        for line in content.splitlines(keepends=True):
            lines.append("    " + line)
        if not content.endswith("\n"):
            lines.append("\n")
    DST.write_text("".join(lines))
    total = sum(p.stat().st_size for p in FILES.values())
    print(f"wrote {DST.relative_to(REPO)} ({total} bytes from {len(FILES)} files)")


if __name__ == "__main__":
    main()
