#!/usr/bin/env python3
"""Regenerate gitops/manifests/pr-pusher/payload-configmap.yaml from src/.

Source of truth = gitops/manifests/pr-pusher/src/push.py.
"""

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "gitops/manifests/pr-pusher/src/push.py"
DST = REPO / "gitops/manifests/pr-pusher/payload-configmap.yaml"

HEADER = """---
# Auto-generated by scripts/regen-pr-pusher-configmap.py from
# gitops/manifests/pr-pusher/src/push.py. Do not hand-edit.
apiVersion: v1
kind: ConfigMap
metadata:
  name: pr-pusher-payload
  namespace: agents
data:
  push.py: |
"""


def main() -> None:
    src = SRC.read_text()
    indented = "".join("    " + line for line in src.splitlines(keepends=True))
    if not indented.endswith("\n"):
        indented += "\n"
    DST.write_text(HEADER + indented)
    print(f"wrote {DST.relative_to(REPO)} ({len(src)} bytes)")


if __name__ == "__main__":
    main()
