#!/usr/bin/env python3
"""Regenerate gitops/manifests/alertmanager-shim/configmap.yaml from app.py.

Source of truth = gitops/manifests/alertmanager-shim/app.py. The ConfigMap
mirrors the file content; run this script after editing app.py.
"""

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "gitops/manifests/alertmanager-shim/app.py"
DST = REPO / "gitops/manifests/alertmanager-shim/configmap.yaml"

HEADER = """---
# Auto-generated by scripts/regen-alertmanager-shim-configmap.py from
# gitops/manifests/alertmanager-shim/app.py. Do not hand-edit; edit the
# .py file and re-run the script.
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-shim-src
  namespace: monitoring
data:
  app.py: |
"""


def main() -> None:
    src = SRC.read_text()
    indented = "".join("    " + line for line in src.splitlines(keepends=True))
    if not indented.endswith("\n"):
        indented += "\n"
    DST.write_text(HEADER + indented)
    print(f"wrote {DST.relative_to(REPO)} ({len(src)} bytes from app.py)")


if __name__ == "__main__":
    main()
