---
apiVersion: v1
kind: Service
metadata:
  name: presidio-anonymizer
  namespace: presidio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: presidio-anonymizer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
