---
k3s_version: "v1.32.1+k3s1"
k3s_install_script_url: "https://get.k3s.io"

k3s_server_args:
  - "--cluster-init"
  - "--disable=traefik"
  - "--disable=servicelb"
  - "--write-kubeconfig-mode=0644"

k3s_kubeconfig_path: /etc/rancher/k3s/k3s.yaml

# Additional TLS SANs for the k3s API server cert. Changing this list causes
# k3s to regenerate its serving cert on next restart.
k3s_tls_san: []
